version: "3.7"
services:
  agreggrator:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "24225:24225"
      - "24225:24225/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./dados/:/dados/
  nginx-syslog:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx-syslog/default.conf:/etc/nginx/conf.d/default.conf
  nginx-waf:
    build: ./nginx-waf
    ports:
      - "8180:80"
    volumes:
      - ./nginx-waf/default.conf:/etc/nginx/conf.d/default.conf
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true  
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    user: 'elasticsearch'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data: